// Code generated by sqlc. DO NOT EDIT.

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type AccountRoles struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	RoleID    uuid.UUID
	CreatedAt time.Time
}

type Accounts struct {
	ID             uuid.UUID
	Username       string
	Hashedpassword string
	Profile        uuid.UUID
	IsBlocked      bool
	CreatedAt      time.Time
}

type Helptext struct {
	ID        uuid.UUID
	TaskID    uuid.UUID
	Helptext  string
	CreatedAt time.Time
}

type Menu struct {
	ID        uuid.UUID
	Name      string
	TaskID    uuid.UUID
	CreatedAt time.Time
}

type Navigation struct {
	ID        uuid.UUID
	Name      string
	TaskID    uuid.UUID
	CreatedAt time.Time
}

type Profiles struct {
	ID                uuid.UUID
	ProfilePicture    string
	ProfileBackground string
	FirstName         string
	LastName          string
	Mobile            string
	Email             string
	CreatedAt         time.Time
}

type RoleTasks struct {
	ID        uuid.UUID
	TaskID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt time.Time
}

type Roles struct {
	ID        uuid.UUID
	Role      string
	CreatedAt time.Time
}

type Tasks struct {
	ID        uuid.UUID
	Task      string
	CreatedAt time.Time
}
